Update action.yaml

diff --git a/.github/workflows/actions/run-test/action.yaml b/.github/workflows/actions/run-test/action.yaml
--- a/.github/workflows/actions/run-test/action.yaml
+++ b/.github/workflows/actions/run-test/action.yaml
@@ -53,14 +53,37 @@ runs:
 
     - name: Check test output
       run: |
-        test_file="examples/tests/${{ inputs.category }}/${{ inputs.sub-category }}/${{ inputs.test-name }}
-        
-        if [[ "${test_file}" == *.txt ]]; then
-          diff output.txt "${test_file}.txt"
-        elif [[ "${test_file}" == *.py ]]; then
-          python3 "${test_file}.py" output.txt
+        test_dir="examples/tests/${{ inputs.category }}/${{ inputs.sub-category }}/${{ inputs.test-name }}"
+    
+        # Find the non-Rust file (either .py or .txt) in the directory
+        nonrust_file=$(find "$test_dir" -type f \( -name "*.py" -o -name "*.txt" \) -print -quit)
+    
+        if [ -z "$nonrust_file" ]; then
+          echo "Error: No non-Rust (py or txt) file found in directory."
+          exit 1
+        fi
+    
+        # Determine the file type and perform comparison
+        if [[ "$nonrust_file" == *.txt ]]; then
+          diff output.txt "$nonrust_file"
+        elif [[ "$nonrust_file" == *.py ]]; then
+          python3 "$nonrust_file" output.txt
         else
-          echo "Unsupported file extension. Only .txt and .py are supported."
+          echo "Unsupported file extension for non-Rust file. Only .txt and .py are supported."
           exit 1
         fi
       shell: bash
+  
+    # - name: Check test output
+    #   run: |
+    #     test_file="examples/tests/${{ inputs.category }}/${{ inputs.sub-category }}/${{ inputs.test-name }}
+        
+    #     if [[ "${test_file}" == *.txt ]]; then
+    #       diff output.txt "${test_file}.txt"
+    #     elif [[ "${test_file}" == *.py ]]; then
+    #       python3 "${test_file}.py" output.txt
+    #     else
+    #       echo "Unsupported file extension. Only .txt and .py are supported."
+    #       exit 1
+    #     fi
+    #   shell: bash
